
export const OPEN_MODAL_ORDER = 'OPEN_MODAL_ORDER';
export const OPEN_MODAL_INGREDIENT = 'OPEN_MODAL_INGREDIENT';
export const OPEN_MODAL_ORDER_DETAILS = 'OPEN_MODAL_ORDER_DETAILS'
export const CLOSE_MODAL = 'CLOSE_MODAL';